services:
  user-service:
    image: myapp/user-service
    tag: latest
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: redis://cache:6379
      DATABASE_URL: postgres://admin:admin123@postgres:5432/microservices
    depends_on:
      - postgres
      - cache

  order-service:
    image: myapp/order-service
    tag: latest
    ports:
      - "3002:3000"
    environment:
      REDIS_URL: redis://cache:6379
      USER_SERVICE_URL: http://user-service:3000
      DATABASE_URL: postgres://admin:admin123@postgres:5432/microservices
    depends_on:
      - postgres
      - cache
      - user-service

  notification-service:
    image: myapp/notification-service
    tag: latest
    ports:
      - "3003:3000"
    environment:
      REDIS_URL: redis://cache:6379
      ORDER_SERVICE_URL: http://order-service:3000
    depends_on:
      - cache

  postgres:
    image: postgres
    tag: "15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

  cache:
    image: redis
    tag: alpine
    ports:
      - "6379:6379"